import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { readFileSync } from "node:fs";
import { execSync } from "node:child_process";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const loadPackageVersion = (packageName) => {
	const packageJsonUrl = new URL(`./node_modules/${packageName}/package.json`, import.meta.url);
	const packageJson = JSON.parse(readFileSync(packageJsonUrl, "utf8"));
	if (!packageJson?.version || typeof packageJson.version !== "string") {
		throw new Error(`[build] Cannot resolve version for ${packageName}`);
	}
	return packageJson.version;
};
const linderaKoVersion = loadPackageVersion("lindera-wasm-ko-dic");
const linderaJaVersion = loadPackageVersion("lindera-wasm-ipadic");
const resolveGitCommit = () => {
	try {
		const commit = execSync("git rev-parse HEAD", { encoding: "utf8" }).trim();
		if (!commit) throw new Error("empty git commit");
		return commit;
	} catch (error) {
		throw new Error(`[build] Cannot resolve git commit for immutable morphology asset URL: ${error instanceof Error ? error.message : String(error)}`);
	}
};
const hiwordsGitCommit = resolveGitCommit();

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	define: {
		__LINDERA_WASM_KO_VERSION__: JSON.stringify(linderaKoVersion),
		__LINDERA_WASM_JA_VERSION__: JSON.stringify(linderaJaVersion),
		__HIWORDS_GIT_COMMIT__: JSON.stringify(hiwordsGitCommit)
	},
	outfile: "main.js",
	minify: prod,
	loader: {
		'.wasm': 'binary'
	}
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
